using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using UnityEngine;
using UnityEngine.AI;
using Unity.AI.Navigation;
using IndoorNavAR.Core.Events;

namespace IndoorNavAR.Navigation
{
    /// <summary>
    /// Generador integrado de NavMesh que usa TODOS los sistemas:
    /// - AR Floor Detection (LiDAR/Depth/Planes)
    /// - Unified Mesh Filtering (triángulos por altura + normal)
    /// - Robust Floor Detection (análisis estadístico)
    /// - Runtime NavMesh con configuración adaptativa
    /// ✅ MEJORADO: Ahora detecta modelos dinámicos automáticamente
    /// </summary>
    public class IntegratedNavMeshGenerator : MonoBehaviour
    {
        [Header("Componentes del Sistema")]
        [SerializeField] private ARFloorReferenceDetector _arFloorDetector;
        [SerializeField] private UnifiedMeshFloorFilter _meshFilter;
        [SerializeField] private RobustFloorDetector _robustFloorDetector;
        
        [Header("Fuente de Geometría")]
        [Tooltip("Mesh unificado del cuarto (piso+paredes+muebles)")]
        [SerializeField] private MeshFilter _roomMeshFilter;
        
        [Tooltip("Layer del mesh del cuarto")]
        [SerializeField] private LayerMask _roomMeshLayers = -1; // Todo por defecto
        
        [Tooltip("Procesar todos los meshes en la escena")]
        [SerializeField] private bool _processAllSceneMeshes = true;
        
        [Tooltip("Buscar modelos dinámicamente si no hay mesh asignado")]
        [SerializeField] private bool _autoDetectDynamicModels = true;
        
        [Tooltip("Nombre/tag del contenedor de modelos")]
        [SerializeField] private string _modelContainerName = "[3D Models]";
        
        [Header("Configuración NavMesh")]
        [SerializeField] private int _navMeshAgentTypeID = 0;
        [SerializeField] private float _agentRadius = 0.3f;
        [SerializeField] private float _agentHeight = 1.8f;
        [SerializeField] private float _maxSlope = 45f;
        [SerializeField] private float _stepHeight = 0.4f;
        
        [Header("Precisión y Calidad")]
        [Tooltip("Tamaño de voxel (más bajo = más preciso, más costoso)")]
        [SerializeField] private float _voxelSize = 0.08f;
        
        [Tooltip("Área mínima navegable (m²) - evita regiones muy pequeñas")]
        [SerializeField] private int _minRegionArea = 2;
        
        [Header("Puertas y Pasillos")]
        [Tooltip("Ajustar agent radius dinámicamente para puertas")]
        [SerializeField] private bool _enableDynamicAgentRadius = true;
        
        [Tooltip("Radio mínimo del agente (para puertas estrechas)")]
        [SerializeField] private float _minAgentRadius = 0.15f;
        
        [Header("Generación Automática")]
        [SerializeField] private bool _autoGenerateOnStart = false;
        [SerializeField] private float _autoGenerateDelay = 3f;
        
        [Header("Espera por Modelo Dinámico")]
        [Tooltip("Tiempo máximo de espera por modelo (segundos)")]
        [SerializeField] private float _modelWaitTimeout = 10f;
        
        [Tooltip("Intervalo de verificación de modelo (segundos)")]
        [SerializeField] private float _modelCheckInterval = 0.5f;
        
        [Header("Debug")]
        [SerializeField] private bool _showDebugVisualization = true;
        [SerializeField] private bool _logDetailedProgress = true;
        
        // Estado interno
        private NavMeshSurface _navMeshSurface;
        private GameObject _floorMeshObject;
        private bool _isGenerating;
        private float _generationStartTime;

        #region Properties

        public bool IsGenerating => _isGenerating;
        public bool IsNavMeshReady => _navMeshSurface != null && _navMeshSurface.navMeshData != null;

        #endregion

        #region Unity Lifecycle

        private void Awake()
        {
            ValidateDependencies();
        }

        private void Start()
        {
            if (_autoGenerateOnStart)
            {
                Invoke(nameof(AutoGenerate), _autoGenerateDelay);
            }
        }

        private void OnEnable()
        {
            // Suscribirse al evento de modelo cargado
            EventBus.Instance.Subscribe<ModelLoadedEvent>(OnModelLoaded);
        }

        private void OnDisable()
        {
            EventBus.Instance.Unsubscribe<ModelLoadedEvent>(OnModelLoaded);
        }

        #endregion

        #region Event Handlers

        /// <summary>
        /// Se llama automáticamente cuando se carga un modelo.
        /// </summary>
        private void OnModelLoaded(ModelLoadedEvent evt)
        {
            Debug.Log($"[IntegratedNavMesh] Modelo detectado: {evt.ModelName}. Iniciando generación de NavMesh...");
            
            // Esperar un momento para que el modelo se asiente
            Invoke(nameof(AutoGenerate), 1f);
        }

        #endregion

        #region Initialization

        private void ValidateDependencies()
        {
            // Auto-buscar componentes si no están asignados
            if (_arFloorDetector == null)
                _arFloorDetector = FindFirstObjectByType<ARFloorReferenceDetector>();
            
            if (_meshFilter == null)
                _meshFilter = FindFirstObjectByType<UnifiedMeshFloorFilter>();
            
            if (_robustFloorDetector == null)
                _robustFloorDetector = FindFirstObjectByType<RobustFloorDetector>();
            
            // Log de estado
            Debug.Log("[IntegratedNavMesh] ========== SISTEMA INICIALIZADO ==========");
            Debug.Log($"  • AR Floor Detector: {(_arFloorDetector != null ? "✅" : "❌")}");
            Debug.Log($"  • Mesh Filter: {(_meshFilter != null ? "✅" : "❌")}");
            Debug.Log($"  • Robust Floor Detector: {(_robustFloorDetector != null ? "✅" : "❌")}");
            Debug.Log($"  • Auto-detect models: {(_autoDetectDynamicModels ? "✅" : "❌")}");
            Debug.Log("==========================================");
        }

        #endregion

        #region Auto-Generation

        private async void AutoGenerate()
        {
            await GenerateCompleteNavMesh();
        }

        #endregion

        #region Public API

        /// <summary>
        /// Genera NavMesh completo usando TODOS los sistemas disponibles.
        /// </summary>
        public async Task<bool> GenerateCompleteNavMesh()
        {
            if (_isGenerating)
            {
                Debug.LogWarning("[IntegratedNavMesh] Generación ya en progreso.");
                return false;
            }
            
            _isGenerating = true;
            _generationStartTime = Time.time;
            
            try
            {
                Debug.Log("[IntegratedNavMesh] ========== INICIO GENERACIÓN ==========");
                
                // ========================================
                // FASE 0: DETECCIÓN DE MODELO DINÁMICO
                // ========================================
                if (_roomMeshFilter == null && _autoDetectDynamicModels)
                {
                    LogProgress("FASE 0/4: Esperando modelo dinámico...");
                    
                    bool modelFound = await WaitForDynamicModel();
                    
                    if (!modelFound)
                    {
                        Debug.LogError("[IntegratedNavMesh] ❌ No se encontró modelo. Verifica que el modelo esté cargado.");
                        
                        EventBus.Instance.Publish(new ShowMessageEvent
                        {
                            Message = "No se encontró modelo 3D. Carga un modelo primero.",
                            Type = MessageType.Error,
                            Duration = 5f
                        });
                        
                        return false;
                    }
                }
                
                // ========================================
                // FASE 1: DETECCIÓN AR DE PISO REAL
                // ========================================
                if (_arFloorDetector != null)
                {
                    LogProgress("FASE 1/4: Detectando piso con AR Foundation...");
                    
                    if (!_arFloorDetector.IsReady)
                    {
                        _arFloorDetector.StartFloorDetection();
                        
                        // Esperar a que termine el escaneo
                        float timeout = 10f;
                        float elapsed = 0f;
                        
                        while (!_arFloorDetector.IsReady && elapsed < timeout)
                        {
                            await Task.Delay(100);
                            elapsed += 0.1f;
                        }
                        
                        if (!_arFloorDetector.IsReady)
                        {
                            Debug.LogWarning("[IntegratedNavMesh] ⚠️ Timeout en detección AR. Continuando con fallback.");
                        }
                    }
                    
                    if (_arFloorDetector.IsReady)
                    {
                        Debug.Log($"[IntegratedNavMesh] ✅ Piso AR detectado: Y={_arFloorDetector.FloorHeight:F3}m ({_arFloorDetector.UsedMethod})");
                    }
                }
                else
                {
                    Debug.LogWarning("[IntegratedNavMesh] ⚠️ AR Floor Detector no disponible. Usando métodos alternativos.");
                }
                
                await Task.Yield();
                
                // ========================================
                // FASE 2: FILTRADO DE MESH UNIFICADO
                // ========================================
                LogProgress("FASE 2/4: Filtrando mesh unificado (piso vs muebles)...");
                
                if (_meshFilter != null)
                {
                    GameObject filteredFloor = null;
                    
                    if (_processAllSceneMeshes)
                    {
                        // Procesar todos los meshes
                        LogProgress("  → Procesando todos los meshes en escena...");
                        filteredFloor = _meshFilter.FilterAllSceneMeshes(_roomMeshLayers);
                    }
                    else if (_roomMeshFilter != null)
                    {
                        // Procesar solo el mesh especificado
                        LogProgress("  → Procesando mesh específico...");
                        filteredFloor = _meshFilter.FilterAndGenerateFloorMesh(_roomMeshFilter);
                    }
                    else
                    {
                        Debug.LogError("[IntegratedNavMesh] ❌ No hay mesh fuente especificado.");
                        
                        EventBus.Instance.Publish(new ShowMessageEvent
                        {
                            Message = "No hay geometría para generar NavMesh.",
                            Type = MessageType.Error,
                            Duration = 5f
                        });
                        
                        return false;
                    }
                    
                    if (filteredFloor != null)
                    {
                        _floorMeshObject = filteredFloor;
                        Debug.Log("[IntegratedNavMesh] ✅ Mesh de piso filtrado correctamente.");
                    }
                    else
                    {
                        Debug.LogError("[IntegratedNavMesh] ❌ Fallo al filtrar mesh. Verifica que el modelo tenga geometría horizontal.");
                        
                        EventBus.Instance.Publish(new ShowMessageEvent
                        {
                            Message = "No se encontró piso en el modelo. Verifica la geometría.",
                            Type = MessageType.Error,
                            Duration = 5f
                        });
                        
                        return false;
                    }
                }
                else
                {
                    Debug.LogWarning("[IntegratedNavMesh] ⚠️ Mesh Filter no disponible.");
                }
                
                await Task.Yield();
                
                // ========================================
                // FASE 3: ANÁLISIS ROBUSTO DE GEOMETRÍA
                // ========================================
                LogProgress("FASE 3/4: Análisis estadístico de geometría...");
                
                if (_robustFloorDetector != null)
                {
                    bool analysisSuccess = _robustFloorDetector.AnalyzeAndPrepareGeometry();
                    
                    if (!analysisSuccess)
                    {
                        Debug.LogWarning("[IntegratedNavMesh] ⚠️ Análisis robusto falló. Continuando...");
                    }
                    else
                    {
                        Debug.Log("[IntegratedNavMesh] ✅ Geometría analizada y preparada.");
                    }
                    
                    // Pausa para que Unity procese NavMeshModifierVolumes
                    await Task.Delay(100);
                }
                
                await Task.Yield();
                
                // ========================================
                // FASE 4: GENERACIÓN DE NAVMESH
                // ========================================
                LogProgress("FASE 4/4: Generando NavMesh...");
                
                bool navMeshSuccess = await BuildNavMesh();
                
                if (!navMeshSuccess)
                {
                    Debug.LogError("[IntegratedNavMesh] ❌ Fallo al generar NavMesh.");
                    
                    EventBus.Instance.Publish(new ShowMessageEvent
                    {
                        Message = "Error generando NavMesh. Revisa la consola.",
                        Type = MessageType.Error,
                        Duration = 5f
                    });
                    
                    return false;
                }
                
                // ========================================
                // FINALIZACIÓN
                // ========================================
                float totalTime = Time.time - _generationStartTime;
                
                Debug.Log("[IntegratedNavMesh] ========== GENERACIÓN COMPLETA ==========");
                Debug.Log($"  ✅ NavMesh generado exitosamente");
                Debug.Log($"  ⏱️ Tiempo total: {totalTime:F2}s");
                Debug.Log($"  📊 Sistema usado: AR + Mesh Filter + Robust Analysis");
                Debug.Log("==========================================");
                
                EventBus.Instance.Publish(new ShowMessageEvent
                {
                    Message = "NavMesh generado con éxito",
                    Type = MessageType.Success,
                    Duration = 3f
                });
                
                return true;
            }
            catch (Exception ex)
            {
                Debug.LogError($"[IntegratedNavMesh] ❌ ERROR: {ex.Message}\n{ex.StackTrace}");
                
                EventBus.Instance.Publish(new ShowMessageEvent
                {
                    Message = $"Error crítico: {ex.Message}",
                    Type = MessageType.Error,
                    Duration = 5f
                });
                
                return false;
            }
            finally
            {
                _isGenerating = false;
            }
        }

        /// <summary>
        /// Limpia todo: NavMesh, mesh filtrado, volúmenes de exclusión.
        /// </summary>
        public void ClearAll()
        {
            // Limpiar NavMesh
            if (_navMeshSurface != null)
            {
                _navMeshSurface.RemoveData();
                Destroy(_navMeshSurface.gameObject);
                _navMeshSurface = null;
            }
            
            // Limpiar mesh filtrado
            if (_floorMeshObject != null)
            {
                Destroy(_floorMeshObject);
                _floorMeshObject = null;
            }
            
            // Limpiar detector robusto
            _robustFloorDetector?.Cleanup();
            
            // Limpiar mesh filter
            _meshFilter?.CleanupPreviousMesh();
            
            Debug.Log("[IntegratedNavMesh] Sistema limpiado completamente.");
        }

        #endregion

        #region Dynamic Model Detection

        /// <summary>
        /// Espera a que un modelo dinámico esté disponible en la escena.
        /// </summary>
        private async Task<bool> WaitForDynamicModel()
        {
            float elapsed = 0f;
            
            EventBus.Instance.Publish(new ShowMessageEvent
            {
                Message = "Buscando modelo 3D en la escena...",
                Type = MessageType.Info,
                Duration = 2f
            });
            
            while (elapsed < _modelWaitTimeout)
            {
                // Buscar modelo dinámicamente
                MeshFilter[] foundMeshes = FindDynamicModelMeshes();
                
                if (foundMeshes != null && foundMeshes.Length > 0)
                {
                    Debug.Log($"[IntegratedNavMesh] ✅ Modelo encontrado: {foundMeshes.Length} meshes detectados");
                    
                    // Si estamos en modo "process all", ya está listo
                    if (_processAllSceneMeshes)
                    {
                        return true;
                    }
                    
                    // Si no, asignar el primer mesh encontrado
                    _roomMeshFilter = foundMeshes[0];
                    Debug.Log($"[IntegratedNavMesh] Usando mesh: {_roomMeshFilter.gameObject.name}");
                    
                    return true;
                }
                
                // Esperar antes de verificar nuevamente
                await Task.Delay((int)(_modelCheckInterval * 1000));
                elapsed += _modelCheckInterval;
                
                LogProgress($"  → Esperando modelo... ({elapsed:F1}s / {_modelWaitTimeout:F1}s)");
            }
            
            Debug.LogWarning($"[IntegratedNavMesh] ⏱️ Timeout esperando modelo ({_modelWaitTimeout}s)");
            return false;
        }

        /// <summary>
        /// Busca meshes de modelos dinámicos en la escena.
        /// </summary>
        private MeshFilter[] FindDynamicModelMeshes()
        {
            List<MeshFilter> validMeshes = new List<MeshFilter>();
            
            // Buscar por nombre de contenedor
            Transform modelContainer = GameObject.Find(_modelContainerName)?.transform;
            
            if (modelContainer != null)
            {
                MeshFilter[] meshes = modelContainer.GetComponentsInChildren<MeshFilter>();
                
                foreach (MeshFilter mf in meshes)
                {
                    if (mf.sharedMesh != null && mf.sharedMesh.vertexCount > 0)
                    {
                        // Verificar que esté en la capa correcta
                        if (_roomMeshLayers == -1 || (_roomMeshLayers.value & (1 << mf.gameObject.layer)) != 0)
                        {
                            validMeshes.Add(mf);
                        }
                    }
                }
            }
            
            // Si no encontramos por contenedor, buscar en toda la escena
            if (validMeshes.Count == 0)
            {
                MeshFilter[] allMeshes = FindObjectsByType<MeshFilter>(FindObjectsSortMode.None);
                
                foreach (MeshFilter mf in allMeshes)
                {
                    if (mf.sharedMesh != null && 
                        mf.sharedMesh.vertexCount > 0 &&
                        !mf.gameObject.name.Contains("Filtered Floor") && // Ignorar mesh filtrado
                        !mf.gameObject.name.Contains("NavMesh"))          // Ignorar NavMesh
                    {
                        if (_roomMeshLayers == -1 || (_roomMeshLayers.value & (1 << mf.gameObject.layer)) != 0)
                        {
                            validMeshes.Add(mf);
                        }
                    }
                }
            }
            
            return validMeshes.ToArray();
        }

        #endregion

        #region NavMesh Building

        /// <summary>
        /// Construye NavMesh usando NavMeshSurface en runtime.
        /// </summary>
        private async Task<bool> BuildNavMesh()
        {
            // Crear NavMeshSurface si no existe
            if (_navMeshSurface == null)
            {
                GameObject surfaceObj = new GameObject("[NavMesh Surface - Integrated]");
                _navMeshSurface = surfaceObj.AddComponent<NavMeshSurface>();
            }
            
            // Configurar NavMeshSurface
            ConfigureNavMeshSurface();
            
            // Construir NavMesh
            try
            {
                await Task.Yield();
                _navMeshSurface.BuildNavMesh();
                await Task.Yield();
                
                // Verificar resultado
                NavMeshTriangulation triangulation = NavMesh.CalculateTriangulation();
                
                if (triangulation.vertices.Length == 0)
                {
                    Debug.LogError("[IntegratedNavMesh] ❌ NavMesh vacío (sin vértices).");
                    Debug.LogError("  → Verifica que el mesh filtrado tenga geometría válida");
                    Debug.LogError("  → Verifica que la capa del mesh esté incluida en Room Mesh Layers");
                    return false;
                }
                
                Debug.Log($"[IntegratedNavMesh] ✅ NavMesh: {triangulation.vertices.Length} vértices, " +
                         $"{triangulation.indices.Length / 3} triángulos");
                
                return true;
            }
            catch (Exception ex)
            {
                Debug.LogError($"[IntegratedNavMesh] ❌ Error en BuildNavMesh: {ex.Message}");
                return false;
            }
        }

        /// <summary>
        /// Configura NavMeshSurface con parámetros optimizados.
        /// </summary>
        private void ConfigureNavMeshSurface()
        {
            // Tipo de agente
            _navMeshSurface.agentTypeID = _navMeshAgentTypeID;
            
            // Modo de recolección
            _navMeshSurface.collectObjects = CollectObjects.All;
            
            // Usar RenderMeshes Y PhysicsColliders (captura todo)
            _navMeshSurface.useGeometry = NavMeshCollectGeometry.RenderMeshes | NavMeshCollectGeometry.PhysicsColliders;
            
            // Layer mask (solo geometría relevante)
            if (_roomMeshLayers != 0)
            {
                _navMeshSurface.layerMask = _roomMeshLayers;
            }
            
            // Precisión del voxel
            _navMeshSurface.overrideVoxelSize = true;
            _navMeshSurface.voxelSize = _voxelSize;
            
            // Área mínima de región
            _navMeshSurface.minRegionArea = _minRegionArea;
            
            // Configurar agente dinámicamente
            if (_enableDynamicAgentRadius)
            {
                // Detectar si hay geometría estrecha (puertas)
                float detectedMinWidth = DetectNarrowestPassage();
                
                if (detectedMinWidth > 0 && detectedMinWidth < _agentRadius * 2f)
                {
                    float adjustedRadius = Mathf.Max(_minAgentRadius, detectedMinWidth * 0.4f);
                    
                    Debug.Log($"[IntegratedNavMesh] 🚪 Pasaje estrecho detectado: {detectedMinWidth:F2}m");
                    Debug.Log($"[IntegratedNavMesh] 🔧 Ajustando agent radius: {_agentRadius:F2}m → {adjustedRadius:F2}m");
                    
                    // Ajustar configuración del agente
                    NavMeshBuildSettings settings = NavMesh.GetSettingsByID(_navMeshAgentTypeID);
                    settings.agentRadius = adjustedRadius;
                    settings.agentHeight = _agentHeight;
                    settings.agentSlope = _maxSlope;
                    settings.agentClimb = _stepHeight;
                }
            }
            
            Debug.Log("[IntegratedNavMesh] ⚙️ NavMeshSurface configurado:");
            Debug.Log($"  • Voxel size: {_voxelSize}m");
            Debug.Log($"  • Min region area: {_minRegionArea}m²");
            Debug.Log($"  • Agent radius: {_agentRadius}m");
            Debug.Log($"  • Agent height: {_agentHeight}m");
        }

        /// <summary>
        /// Detecta el pasaje más estrecho en la geometría (puertas).
        /// </summary>
        private float DetectNarrowestPassage()
        {
            if (_floorMeshObject == null)
                return 0f;
            
            MeshFilter mf = _floorMeshObject.GetComponent<MeshFilter>();
            if (mf == null || mf.sharedMesh == null)
                return 0f;
            
            // Analizar bounds del mesh
            Bounds bounds = mf.sharedMesh.bounds;
            
            // Detectar dimensión más pequeña (ancho mínimo)
            float minDimension = Mathf.Min(bounds.size.x, bounds.size.z);
            
            return minDimension;
        }

        #endregion

        #region Logging

        private void LogProgress(string message)
        {
            if (!_logDetailedProgress)
                return;
            
            Debug.Log($"[IntegratedNavMesh] {message}");
        }

        #endregion

        #region Debug Menu

        [ContextMenu("Generate NavMesh")]
        private void DebugGenerate()
        {
            _ = GenerateCompleteNavMesh();
        }

        [ContextMenu("Clear All")]
        private void DebugClear()
        {
            ClearAll();
        }

        [ContextMenu("Find Dynamic Models")]
        private void DebugFindModels()
        {
            MeshFilter[] meshes = FindDynamicModelMeshes();
            Debug.Log($"[IntegratedNavMesh] Modelos encontrados: {meshes.Length}");
            
            foreach (MeshFilter mf in meshes)
            {
                Debug.Log($"  → {mf.gameObject.name} ({mf.sharedMesh.vertexCount} vértices)");
            }
        }

        #endregion

        #region Gizmos

        private void OnDrawGizmos()
        {
            if (!_showDebugVisualization)
                return;
            
            // Dibujar NavMeshSurface
            if (_navMeshSurface != null)
            {
                Gizmos.color = new Color(0f, 1f, 0f, 0.3f);
                Gizmos.matrix = _navMeshSurface.transform.localToWorldMatrix;
                Gizmos.DrawCube(_navMeshSurface.center, _navMeshSurface.size);
                
                Gizmos.color = Color.green;
                Gizmos.DrawWireCube(_navMeshSurface.center, _navMeshSurface.size);
                Gizmos.matrix = Matrix4x4.identity;
            }
            
            // Dibujar mesh de piso filtrado
            if (_floorMeshObject != null)
            {
                MeshFilter mf = _floorMeshObject.GetComponent<MeshFilter>();
                if (mf != null && mf.sharedMesh != null)
                {
                    Gizmos.color = new Color(0f, 1f, 1f, 0.5f);
                    Gizmos.DrawWireMesh(
                        mf.sharedMesh,
                        _floorMeshObject.transform.position,
                        _floorMeshObject.transform.rotation
                    );
                }
            }
        }

        #endregion
    }
}