using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using UnityEngine;
using UnityEngine.AI;
using UnityEngine.XR.ARFoundation;
using UnityEngine.XR.ARSubsystems;
using Unity.AI.Navigation;
using IndoorNavAR.Core.Events;

namespace IndoorNavAR.Navigation
{
    /// <summary>
    /// Generador avanzado de NavMesh con análisis completo de geometría.
    /// ✅ PROFESIONAL: Detecta pisos, paredes, obstáculos y genera rutas precisas.
    /// </summary>
    public class NavMeshGenerator : MonoBehaviour
    {
        [Header("Configuración NavMesh")]
        [SerializeField] private int _navMeshAgentTypeID = 0;
        [SerializeField] private float _agentRadius = 0.3f;
        [SerializeField] private float _agentHeight = 1.8f;
        [SerializeField] private float _maxSlope = 45f;
        [SerializeField] private float _stepHeight = 0.4f;

        [Header("Análisis de Geometría")]
        [SerializeField] private bool _analyzeCompleteGeometry = true;
        [SerializeField] private float _voxelSize = 0.08f; // Precisión del escaneo (más bajo = más preciso)
        [SerializeField] private int _minRegionArea = 2; // Área mínima navegable
        
        [Header("Detección de Obstáculos")]
        [SerializeField] private bool _detectWalls = true;
        [SerializeField] private bool _detectFurniture = true;
        [SerializeField] private float _wallDetectionAngle = 60f; // Ángulo para detectar paredes
        [SerializeField] private LayerMask _obstacleLayerMask;

        [Header("Generación Automática")]
        [SerializeField] private bool _autoGenerateOnStart = true;
        [SerializeField] private float _autoGenerateDelay = 2f;
        [SerializeField] private bool _debugVisualization = true;

        [Header("Referencias")]
        [SerializeField] private LayerMask _navMeshLayer;

        // Estado interno
        private NavMeshSurface _mainSurface;
        private Transform _surfacesParent;
        private List<GameObject> _detectedObstacles = new List<GameObject>();
        private Bounds _scannedBounds;
        private bool _isGenerating;
        private float _lastGenerationTime;

        #region Properties

        public bool IsGenerating => _isGenerating;
        public int ObstacleCount => _detectedObstacles.Count;
        public Bounds ScannedBounds => _scannedBounds;

        #endregion

        #region Unity Lifecycle

        private void Awake()
        {
            Initialize();
        }

        private void Start()
        {
            if (_autoGenerateOnStart)
            {
                Invoke(nameof(AutoGenerateNavMesh), _autoGenerateDelay);
            }
        }

        #endregion

        #region Initialization

        private void Initialize()
        {
            CreateSurfacesParent();
            ConfigureNavMeshLayer();
            ValidateNavMeshSettings();
            
            Debug.Log("[NavMeshGenerator] Sistema avanzado de NavMesh inicializado.");
        }

        private void CreateSurfacesParent()
        {
            GameObject parent = new GameObject("[NavMesh System]");
            _surfacesParent = parent.transform;
        }

        private void ConfigureNavMeshLayer()
        {
            if (_navMeshLayer == 0)
                _navMeshLayer = LayerMask.GetMask("Default");
            
            if (_obstacleLayerMask == 0)
                _obstacleLayerMask = _navMeshLayer;
        }

        private void ValidateNavMeshSettings()
        {
            // Verificar que exista el NavMesh Agent Type
            NavMeshBuildSettings settings = NavMesh.GetSettingsByID(_navMeshAgentTypeID);
            if (settings.agentTypeID == -1)
            {
                Debug.LogWarning("[NavMeshGenerator] Agent Type no encontrado. Creando configuración por defecto.");
            }
        }

        #endregion

        #region Auto-Generation

        private async void AutoGenerateNavMesh()
        {
            Debug.Log("[NavMeshGenerator] 🚀 Iniciando generación automática de NavMesh...");
            await GenerateAdvancedNavMesh();
        }

        #endregion

        #region Advanced NavMesh Generation

        /// <summary>
        /// Genera NavMesh profesional con análisis completo de geometría.
        /// </summary>
        public async Task<bool> GenerateAdvancedNavMesh()
        {
            if (_isGenerating)
            {
                Debug.LogWarning("[NavMeshGenerator] Generación ya en progreso.");
                return false;
            }

            _isGenerating = true;
            _lastGenerationTime = Time.time;

            try
            {
                Debug.Log("[NavMeshGenerator] ========== ANÁLISIS DE ESCENA ==========");

                // Paso 1: Analizar la escena completa
                SceneAnalysis analysis = await AnalyzeScene();

                if (!analysis.isValid)
                {
                    Debug.LogError("[NavMeshGenerator] ❌ Análisis de escena falló.");
                    return false;
                }

                // Paso 2: Crear NavMesh Surface principal
                CreateMainNavMeshSurface(analysis);

                // Paso 3: Configurar parámetros avanzados
                ConfigureAdvancedNavMesh(analysis);

                // Paso 4: Generar NavMesh
                bool success = await BuildNavMesh();

                if (success)
                {
                    // Paso 5: Post-procesamiento
                    await PostProcessNavMesh(analysis);
                    
                    LogGenerationResults(analysis);
                }

                return success;
            }
            catch (Exception ex)
            {
                Debug.LogError($"[NavMeshGenerator] ❌ Error: {ex.Message}\n{ex.StackTrace}");
                return false;
            }
            finally
            {
                _isGenerating = false;
            }
        }

        /// <summary>
        /// Analiza la escena completa: geometría, obstáculos, superficies navegables.
        /// </summary>
        private async Task<SceneAnalysis> AnalyzeScene()
        {
            Debug.Log("[NavMeshGenerator] 📊 Analizando geometría de la escena...");

            SceneAnalysis analysis = new SceneAnalysis();
            await Task.Yield();

            // 1. Detectar todos los renderers (geometría visible)
            Renderer[] allRenderers = FindObjectsByType<Renderer>(FindObjectsSortMode.None);
            List<Renderer> validRenderers = new List<Renderer>();

            foreach (Renderer renderer in allRenderers)
            {
                // Filtrar por capa
                if ((_navMeshLayer.value & (1 << renderer.gameObject.layer)) != 0)
                {
                    validRenderers.Add(renderer);
                }
            }

            analysis.totalRenderers = validRenderers.Count;

            if (validRenderers.Count == 0)
            {
                Debug.LogError("[NavMeshGenerator] No se encontró geometría en la escena.");
                analysis.isValid = false;
                return analysis;
            }

            // 2. Calcular bounds total de la escena
            analysis.sceneBounds = CalculateCombinedBounds(validRenderers);
            _scannedBounds = analysis.sceneBounds;

            Debug.Log($"[NavMeshGenerator] 📐 Bounds de escena: Tamaño={analysis.sceneBounds.size}, Centro={analysis.sceneBounds.center}");

            // 3. Analizar geometría por tipo
            await AnalyzeGeometryTypes(validRenderers, analysis);

            // 4. Detectar obstáculos
            if (_detectWalls || _detectFurniture)
            {
                await DetectObstacles(validRenderers, analysis);
            }

            analysis.isValid = true;
            return analysis;
        }

        /// <summary>
        /// Analiza tipos de geometría: horizontal (pisos), vertical (paredes), oblicua.
        /// </summary>
        private async Task AnalyzeGeometryTypes(List<Renderer> renderers, SceneAnalysis analysis)
        {
            Debug.Log("[NavMeshGenerator] 🔍 Clasificando geometría...");

            foreach (Renderer renderer in renderers)
            {
                await Task.Yield();

                MeshFilter meshFilter = renderer.GetComponent<MeshFilter>();
                if (meshFilter == null || meshFilter.sharedMesh == null)
                    continue;

                // Analizar normales del mesh para determinar orientación
                GeometryType geoType = ClassifyGeometry(meshFilter, renderer.transform);

                switch (geoType)
                {
                    case GeometryType.Horizontal:
                        analysis.floorSurfaces.Add(renderer);
                        analysis.walkableArea += CalculateHorizontalArea(renderer.bounds);
                        break;
                    
                    case GeometryType.Vertical:
                        analysis.wallSurfaces.Add(renderer);
                        break;
                    
                    case GeometryType.Oblique:
                        analysis.obstacleSurfaces.Add(renderer);
                        break;
                }
            }

            Debug.Log($"[NavMeshGenerator] ✅ Clasificación:");
            Debug.Log($"  - Pisos: {analysis.floorSurfaces.Count} ({analysis.walkableArea:F1}m²)");
            Debug.Log($"  - Paredes: {analysis.wallSurfaces.Count}");
            Debug.Log($"  - Obstáculos: {analysis.obstacleSurfaces.Count}");
        }

        /// <summary>
        /// Clasifica geometría según sus normales.
        /// </summary>
        private GeometryType ClassifyGeometry(MeshFilter meshFilter, Transform transform)
        {
            Mesh mesh = meshFilter.sharedMesh;
            Vector3[] normals = mesh.normals;

            if (normals == null || normals.Length == 0)
                return GeometryType.Oblique;

            // Calcular normal promedio en world space
            Vector3 avgNormal = Vector3.zero;
            foreach (Vector3 normal in normals)
            {
                avgNormal += transform.TransformDirection(normal);
            }
            avgNormal = (avgNormal / normals.Length).normalized;

            // Calcular ángulo con la vertical
            float angleWithUp = Vector3.Angle(avgNormal, Vector3.up);

            // Clasificar
            if (angleWithUp < 30f) // Casi horizontal
                return GeometryType.Horizontal;
            else if (angleWithUp > _wallDetectionAngle) // Casi vertical
                return GeometryType.Vertical;
            else
                return GeometryType.Oblique;
        }

        /// <summary>
        /// Detecta obstáculos específicos (paredes, muebles, objetos).
        /// </summary>
        private async Task DetectObstacles(List<Renderer> renderers, SceneAnalysis analysis)
        {
            Debug.Log("[NavMeshGenerator] 🚧 Detectando obstáculos...");

            _detectedObstacles.Clear();

            foreach (Renderer renderer in renderers)
            {
                await Task.Yield();

                // Verificar si es un obstáculo (vertical u oblicuo)
                if (analysis.wallSurfaces.Contains(renderer) || analysis.obstacleSurfaces.Contains(renderer))
                {
                    // Asegurar que tenga collider para NavMesh
                    EnsureObstacleCollider(renderer.gameObject);
                    _detectedObstacles.Add(renderer.gameObject);
                }
            }

            analysis.obstacleCount = _detectedObstacles.Count;
            Debug.Log($"[NavMeshGenerator] 🚧 {_detectedObstacles.Count} obstáculos detectados y configurados.");
        }

        /// <summary>
        /// Asegura que un obstáculo tenga collider para NavMesh.
        /// </summary>
        private void EnsureObstacleCollider(GameObject obj)
        {
            Collider existingCollider = obj.GetComponent<Collider>();
            
            if (existingCollider != null)
            {
                // Ya tiene collider, asegurar que no sea trigger
                existingCollider.isTrigger = false;
                return;
            }

            // Agregar MeshCollider si tiene MeshFilter
            MeshFilter meshFilter = obj.GetComponent<MeshFilter>();
            if (meshFilter != null && meshFilter.sharedMesh != null)
            {
                MeshCollider meshCollider = obj.AddComponent<MeshCollider>();
                meshCollider.sharedMesh = meshFilter.sharedMesh;
                meshCollider.convex = false;
                meshCollider.isTrigger = false;
            }
            else
            {
                // Fallback: BoxCollider basado en bounds
                BoxCollider boxCollider = obj.AddComponent<BoxCollider>();
                
                Renderer renderer = obj.GetComponent<Renderer>();
                if (renderer != null)
                {
                    Bounds localBounds = renderer.bounds;
                    boxCollider.center = obj.transform.InverseTransformPoint(localBounds.center);
                    boxCollider.size = localBounds.size;
                }
            }
        }

        #endregion

        #region NavMesh Surface Creation

        /// <summary>
        /// Crea la superficie NavMesh principal con configuración avanzada.
        /// </summary>
        private void CreateMainNavMeshSurface(SceneAnalysis analysis)
        {
            Debug.Log("[NavMeshGenerator] 🏗️ Creando superficie NavMesh principal...");

            // Limpiar superficie anterior
            if (_mainSurface != null)
            {
                Destroy(_mainSurface.gameObject);
            }

            // Crear nuevo GameObject para la superficie
            GameObject surfaceObj = new GameObject("[NavMesh Main Surface]");
            surfaceObj.transform.SetParent(_surfacesParent);
            
            // Posicionar en el piso de la escena
            Vector3 floorPosition = analysis.sceneBounds.center;
            floorPosition.y = analysis.sceneBounds.min.y + 0.05f;
            
            surfaceObj.transform.position = floorPosition;
            surfaceObj.transform.rotation = Quaternion.identity;
            surfaceObj.layer = GetLayerFromMask(_navMeshLayer);

            // Agregar componente NavMeshSurface
            _mainSurface = surfaceObj.AddComponent<NavMeshSurface>();

            Debug.Log("[NavMeshGenerator] ✅ Superficie principal creada.");
        }

        /// <summary>
        /// Configura parámetros avanzados del NavMesh.
        /// </summary>
        private void ConfigureAdvancedNavMesh(SceneAnalysis analysis)
        {
            Debug.Log("[NavMeshGenerator] ⚙️ Configurando parámetros avanzados...");

            // Configuración básica
            _mainSurface.agentTypeID = _navMeshAgentTypeID;
            _mainSurface.collectObjects = CollectObjects.Volume;
            
            // ✅ CRÍTICO: Usar RenderMeshes para escanear toda la geometría visible
            _mainSurface.useGeometry = NavMeshCollectGeometry.RenderMeshes;
            
            // Filtro de capas
            _mainSurface.layerMask = _navMeshLayer;

            // ✅ PRECISIÓN: Configurar tamaño de voxel para análisis detallado
            _mainSurface.overrideVoxelSize = true;
            _mainSurface.voxelSize = _voxelSize;

            // ✅ ÁREA MÍNIMA: Filtrar regiones muy pequeñas
            _mainSurface.minRegionArea = _minRegionArea;

            // Calcular volumen de escaneo dinámicamente
            Vector3 scanSize = analysis.sceneBounds.size;
            
            // Agregar margen generoso para capturar todo
            scanSize.x += 4f;
            scanSize.z += 4f;
            scanSize.y = Mathf.Max(scanSize.y * 1.5f, 5f);

            _mainSurface.size = scanSize;
            
            // Centro ajustado para escanear desde el piso hacia arriba
            Vector3 center = Vector3.zero;
            center.y = scanSize.y / 2f;
            _mainSurface.center = center;

            Debug.Log($"[NavMeshGenerator] ⚙️ Configuración:");
            Debug.Log($"  - Volumen de escaneo: {scanSize.x:F1}x{scanSize.y:F1}x{scanSize.z:F1}m");
            Debug.Log($"  - Voxel size: {_voxelSize}m (precisión)");
            Debug.Log($"  - Min region area: {_minRegionArea}m²");
            Debug.Log($"  - Usando: RenderMeshes + PhysicsColliders");
        }

        #endregion

        #region NavMesh Building

        /// <summary>
        /// Construye el NavMesh con la configuración establecida.
        /// </summary>
        private async Task<bool> BuildNavMesh()
        {
            Debug.Log("[NavMeshGenerator] 🔨 Construyendo NavMesh...");

            EventBus.Instance.Publish(new ShowMessageEvent
            {
                Message = "Generando malla de navegación avanzada...",
                Type = MessageType.Info,
                Duration = 2f
            });

            try
            {
                // Construir NavMesh (operación síncrona, pero yield para UI)
                await Task.Yield();
                _mainSurface.BuildNavMesh();
                await Task.Yield();

                // Verificar que se generó correctamente
                NavMeshTriangulation triangulation = NavMesh.CalculateTriangulation();
                
                if (triangulation.vertices.Length == 0)
                {
                    Debug.LogError("[NavMeshGenerator] ❌ NavMesh generado pero sin vértices.");
                    return false;
                }

                Debug.Log($"[NavMeshGenerator] ✅ NavMesh construido: {triangulation.vertices.Length} vértices, {triangulation.indices.Length / 3} triángulos");

                return true;
            }
            catch (Exception ex)
            {
                Debug.LogError($"[NavMeshGenerator] ❌ Error construyendo NavMesh: {ex.Message}");
                return false;
            }
        }

        #endregion

        #region Post-Processing

        /// <summary>
        /// Post-procesa el NavMesh generado para optimización.
        /// </summary>
        private async Task PostProcessNavMesh(SceneAnalysis analysis)
        {
            Debug.Log("[NavMeshGenerator] 🔧 Post-procesando NavMesh...");
            await Task.Yield();

            // Calcular estadísticas del NavMesh generado
            NavMeshTriangulation triangulation = NavMesh.CalculateTriangulation();
            float meshArea = CalculateNavMeshArea(triangulation);

            Debug.Log($"[NavMeshGenerator] 📊 Área navegable generada: {meshArea:F1}m²");

            // Verificar conectividad
            ValidateNavMeshConnectivity();
        }

        /// <summary>
        /// Calcula el área total del NavMesh generado.
        /// </summary>
        private float CalculateNavMeshArea(NavMeshTriangulation triangulation)
        {
            float totalArea = 0f;

            for (int i = 0; i < triangulation.indices.Length; i += 3)
            {
                Vector3 v1 = triangulation.vertices[triangulation.indices[i]];
                Vector3 v2 = triangulation.vertices[triangulation.indices[i + 1]];
                Vector3 v3 = triangulation.vertices[triangulation.indices[i + 2]];

                // Área del triángulo
                Vector3 side1 = v2 - v1;
                Vector3 side2 = v3 - v1;
                float area = Vector3.Cross(side1, side2).magnitude * 0.5f;
                totalArea += area;
            }

            return totalArea;
        }

        /// <summary>
        /// Valida que el NavMesh tenga conectividad adecuada.
        /// </summary>
        private void ValidateNavMeshConnectivity()
        {
            // Verificar que hay camino entre puntos clave
            Vector3 testStart = _scannedBounds.center;
            testStart.y = _scannedBounds.min.y + 0.5f;

            NavMeshHit hit;
            if (NavMesh.SamplePosition(testStart, out hit, 5f, NavMesh.AllAreas))
            {
                Debug.Log("[NavMeshGenerator] ✅ NavMesh conectado correctamente.");
            }
            else
            {
                Debug.LogWarning("[NavMeshGenerator] ⚠️ Problemas de conectividad detectados.");
            }
        }

        #endregion

        #region Results Logging

        /// <summary>
        /// Registra los resultados finales de la generación.
        /// </summary>
        private void LogGenerationResults(SceneAnalysis analysis)
        {
            float generationTime = Time.time - _lastGenerationTime;

            Debug.Log("[NavMeshGenerator] ========== RESULTADOS ==========");
            Debug.Log($"✅ NavMesh generado exitosamente");
            Debug.Log($"⏱️ Tiempo: {generationTime:F2}s");
            Debug.Log($"📐 Área escaneada: {_scannedBounds.size.x:F1}x{_scannedBounds.size.z:F1}m");
            Debug.Log($"🚶 Área navegable: {analysis.walkableArea:F1}m²");
            Debug.Log($"🏠 Geometría analizada: {analysis.totalRenderers} objetos");
            Debug.Log($"🚧 Obstáculos detectados: {analysis.obstacleCount}");
            Debug.Log($"🎯 Precisión (voxel): {_voxelSize}m");
            Debug.Log("=======================================");

            EventBus.Instance.Publish(new ShowMessageEvent
            {
                Message = $"NavMesh generado: {analysis.walkableArea:F0}m² navegables",
                Type = MessageType.Success,
                Duration = 3f
            });

            EventBus.Instance.Publish(new NavMeshGeneratedEvent
            {
                SurfaceCount = 1,
                TotalArea = analysis.walkableArea,
                Success = true
            });
        }

        #endregion

        #region Utilities

        private Bounds CalculateCombinedBounds(List<Renderer> renderers)
        {
            if (renderers.Count == 0)
                return new Bounds();

            Bounds combined = renderers[0].bounds;
            for (int i = 1; i < renderers.Count; i++)
            {
                combined.Encapsulate(renderers[i].bounds);
            }

            return combined;
        }

        private float CalculateHorizontalArea(Bounds bounds)
        {
            return bounds.size.x * bounds.size.z;
        }

        private int GetLayerFromMask(LayerMask mask)
        {
            int layerNumber = 0;
            int layer = mask.value;
            
            while (layer > 1)
            {
                layer >>= 1;
                layerNumber++;
            }
            
            return layerNumber;
        }

        #endregion

        #region Public API

        /// <summary>
        /// Regenera el NavMesh manualmente.
        /// </summary>
        public async Task<bool> RegenerateNavMesh()
        {
            return await GenerateAdvancedNavMesh();
        }

        /// <summary>
        /// Limpia el NavMesh actual.
        /// </summary>
        public void ClearNavMesh()
        {
            if (_mainSurface != null)
            {
                _mainSurface.RemoveData();
                Destroy(_mainSurface.gameObject);
                _mainSurface = null;
            }

            _detectedObstacles.Clear();
            Debug.Log("[NavMeshGenerator] NavMesh limpiado.");
        }

        #endregion

        #region Debug

        [ContextMenu("Generate Advanced NavMesh")]
        private void DebugGenerate()
        {
            _ = GenerateAdvancedNavMesh();
        }

        [ContextMenu("Clear NavMesh")]
        private void DebugClear()
        {
            ClearNavMesh();
        }

        private void OnDrawGizmos()
        {
            if (!_debugVisualization)
                return;

            // Dibujar bounds de escaneo
            if (_scannedBounds.size != Vector3.zero)
            {
                Gizmos.color = new Color(1f, 1f, 0f, 0.2f);
                Gizmos.DrawCube(_scannedBounds.center, _scannedBounds.size);
                
                Gizmos.color = Color.yellow;
                Gizmos.DrawWireCube(_scannedBounds.center, _scannedBounds.size);
            }

            // Dibujar NavMesh Surface
            if (_mainSurface != null)
            {
                Gizmos.color = new Color(0f, 1f, 0f, 0.3f);
                Gizmos.matrix = _mainSurface.transform.localToWorldMatrix;
                Gizmos.DrawCube(_mainSurface.center, _mainSurface.size);
                
                Gizmos.color = Color.green;
                Gizmos.DrawWireCube(_mainSurface.center, _mainSurface.size);
            }

            // Dibujar obstáculos detectados
            Gizmos.color = Color.red;
            foreach (GameObject obstacle in _detectedObstacles)
            {
                if (obstacle != null)
                {
                    Renderer renderer = obstacle.GetComponent<Renderer>();
                    if (renderer != null)
                    {
                        Gizmos.DrawWireCube(renderer.bounds.center, renderer.bounds.size);
                    }
                }
            }
        }

        #endregion

        #region Data Structures

        /// <summary>
        /// Estructura de análisis de escena.
        /// </summary>
        private class SceneAnalysis
        {
            public bool isValid;
            public Bounds sceneBounds;
            public int totalRenderers;
            public float walkableArea;
            public int obstacleCount;
            
            public List<Renderer> floorSurfaces = new List<Renderer>();
            public List<Renderer> wallSurfaces = new List<Renderer>();
            public List<Renderer> obstacleSurfaces = new List<Renderer>();
        }

        /// <summary>
        /// Tipos de geometría detectados.
        /// </summary>
        private enum GeometryType
        {
            Horizontal,  // Pisos, superficies caminables
            Vertical,    // Paredes, muros
            Oblique      // Rampas, obstáculos inclinados
        }

        #endregion
    }
}